/**
 * Stable error codes returned by DxFeed server actions / API routes.
 * Client maps these to localized messages via formatDxFeedError().
 */

export const DxFeedErrorCode = {
  CONFIG_NOT_SET: 'CONFIG_NOT_SET',
  PROP_FIRM_REQUIRED: 'PROP_FIRM_REQUIRED',
  PROP_FIRM_UNSUPPORTED: 'PROP_FIRM_UNSUPPORTED',
  PROP_FIRMS_UNAVAILABLE: 'PROP_FIRMS_UNAVAILABLE',
  USER_NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',
  AUTH_HTTP_ERROR: 'AUTH_HTTP_ERROR',
  AUTH_REJECTED: 'AUTH_REJECTED',
  AUTH_PROP_FIRM_MISMATCH: 'AUTH_PROP_FIRM_MISMATCH',
  HISTORICAL_HOST_UNRESOLVED: 'HISTORICAL_HOST_UNRESOLVED',
  AUTH_UNEXPECTED: 'AUTH_UNEXPECTED',
  INVALID_STORED_CREDENTIALS: 'INVALID_STORED_CREDENTIALS',
  MISSING_PROP_FIRM_RECONNECT: 'MISSING_PROP_FIRM_RECONNECT',
  NO_TOKEN_RECONNECT: 'NO_TOKEN_RECONNECT',
  DUPLICATE_TRADES: 'DUPLICATE_TRADES',
  SYNC_FAILED: 'SYNC_FAILED',
  SAVE_TRADES_FAILED: 'SAVE_TRADES_FAILED',
  ACCOUNT_ID_REQUIRED: 'ACCOUNT_ID_REQUIRED',
  LOAD_SYNCHRONIZATIONS_FAILED: 'LOAD_SYNCHRONIZATIONS_FAILED',
  DELETE_SYNC_FAILED: 'DELETE_SYNC_FAILED',
  UPDATE_SYNC_TIME_FAILED: 'UPDATE_SYNC_TIME_FAILED',
  UNKNOWN: 'UNKNOWN',
} as const

export type DxFeedErrorCodeValue = (typeof DxFeedErrorCode)[keyof typeof DxFeedErrorCode]

export type DxFeedErrorParams = Record<string, string | number>

export function isDxFeedErrorCode(value: string): value is DxFeedErrorCodeValue {
  return Object.values(DxFeedErrorCode).includes(value as DxFeedErrorCodeValue)
}
