export const FPS = 30;
export const SLIDE_FRAMES = 8;

export const LOGO_FRAMES = 48;
export const HEADLINE_FRAMES = 102;
export const PRODUCT_FRAMES = 132;
export const CTA_FRAMES = 66;

export const HEADLINE_START = LOGO_FRAMES - SLIDE_FRAMES;
export const PRODUCT_START = HEADLINE_START + HEADLINE_FRAMES - SLIDE_FRAMES;
export const CTA_START = PRODUCT_START + PRODUCT_FRAMES - SLIDE_FRAMES;

export const PROMO_DURATION_FRAMES =
  LOGO_FRAMES + HEADLINE_FRAMES + PRODUCT_FRAMES + CTA_FRAMES - SLIDE_FRAMES * 3;
