/** R | Protocol API template IDs (from Reference Guide 0.89.0.0). */
export const RithmicTemplateId = {
  LOGIN_REQUEST: 10,
  LOGIN_RESPONSE: 11,
  LOGOUT_REQUEST: 12,
  LOGOUT_RESPONSE: 13,
  RITHMIC_SYSTEM_INFO_REQUEST: 16,
  RITHMIC_SYSTEM_INFO_RESPONSE: 17,
  HEARTBEAT_REQUEST: 18,
  HEARTBEAT_RESPONSE: 19,
  RITHMIC_SYSTEM_GATEWAY_INFO_REQUEST: 20,
  RITHMIC_SYSTEM_GATEWAY_INFO_RESPONSE: 21,
  REJECT: 75,

  LOGIN_INFO_REQUEST: 300,
  LOGIN_INFO_RESPONSE: 301,
  ACCOUNT_LIST_REQUEST: 302,
  ACCOUNT_LIST_RESPONSE: 303,

  SHOW_ORDER_HISTORY_DATES_REQUEST: 318,
  SHOW_ORDER_HISTORY_DATES_RESPONSE: 319,
  SHOW_ORDER_HISTORY_REQUEST: 322,
  SHOW_ORDER_HISTORY_RESPONSE: 323,
  SHOW_ORDER_HISTORY_SUMMARY_REQUEST: 324,
  SHOW_ORDER_HISTORY_SUMMARY_RESPONSE: 325,
  SHOW_ORDER_HISTORY_DETAIL_REQUEST: 326,
  SHOW_ORDER_HISTORY_DETAIL_RESPONSE: 327,

  TRADE_ROUTE: 350,
  RITHMIC_ORDER_NOTIFICATION: 351,
  EXCHANGE_ORDER_NOTIFICATION: 352,

  // PnL plant
  PNL_POSITION_UPDATES_REQUEST: 400,
  PNL_POSITION_UPDATES_RESPONSE: 401,
  PNL_POSITION_SNAPSHOT_REQUEST: 402,
  PNL_POSITION_SNAPSHOT_RESPONSE: 403,
  INSTRUMENT_PNL_POSITION_UPDATE: 450,
  ACCOUNT_PNL_POSITION_UPDATE: 451,

  REPLAY_EXECUTIONS_REQUEST: 3506,
  REPLAY_EXECUTIONS_RESPONSE: 3507,
  SHOW_FILL_HISTORY_REQUEST: 3512,
  SHOW_FILL_HISTORY_RESPONSE: 3513,
} as const

export const TICKER_PLANT = 1
export const ORDER_PLANT = 2
export const HISTORY_PLANT = 3
export const PNL_PLANT = 4
export const REPOSITORY_PLANT = 5

/** ExchangeOrderNotification.NotifyType.FILL */
export const EXCHANGE_NOTIFY_FILL = 5
